### ISSUE TITLE
[Suggestion] Make it be more customizable

### ISSUE THREAD

**Issue by trmdi** [ishovkun/SierraBreeze#1]
What do you think about this ? User can change:

- The titlebar's height
- The space between buttons
- The pixel size of buttons (not just: small/normal/big)

**Comment by ishovkun** [comment]
Title bar height is now such a simple matter since it gets deduced from both the font size and the button size in Breeze. If you agree to narrow the suggestion down to button size/spacing in pixels, I might look into it at some point.

**Comment by Tromzy** [comment]
I agree that buttons on "Normal" size are too big and "Small" are too tiny, so it would be cool to be able to change their size by pixel.

**Comment by ishovkun** [comment]
Guys, I'm putting it on the backburner.

**Comment by ishovkun** [comment]
I haven't added any customizations, but I changed the default values for tiny/small/default etc buttom sizes. Let me know if that works even a little better.

**Comment by trmdi** [comment]
Did you commit it ? @ishovkun

**Comment by trmdi** [comment]
The size looks ok, but I think the space between the buttons need to be a bit shorter.

**Comment by MggMuggins** [comment]
Would there also be a way to change the top border radius? It's a little on the curved side for my liking:
![topborder](https://user-images.githubusercontent.com/16041213/36430497-ecc24bb8-161a-11e8-961c-88dc12cc6a83.png)
