### ISSUE TITLE
white bar at the buttom 

### ISSUE THREAD

**Issue by Madkita** [ishovkun/SierraBreeze#12]
am seeing this white bar at the bottom of any non maximized window  
i do have borders turned off from theme settings and the settings page 
here is a screenshot of reference 

![screenshot_20180113_211854](https://user-images.githubusercontent.com/10248473/34906384-a1c5d5f2-f8a7-11e7-816b-e52919d15ea4.png)

**Comment by trmdi** [comment]
Sorry, what app do you use to print the System Info in the picture ?

**Comment by ishovkun** [comment]
@Madkita , did you disable borders in Settings->Application style->Window decoration-> Border size?

**Comment by Madkita** [comment]
yes its set to no side borders 
after changing it to no border it disappeared 
thanks for your help

**Comment by Madkita** [comment]
@trmdi its a custom script i wrote you can find it on scrips repo
