### ISSUE TITLE
Rounded corners not always used

### ISSUE THREAD

**Issue by Magentium-Chris** [ishovkun/SierraBreeze#15]
I've noticed that when minimizing and maximising windows, they randomly will apply the orunded corners, and will sometimes show sharp corners. I've attached a picture of what I mean. Would this be a setting or perhaps just a bug in Breeze?
![screenshot_20180224_221916](https://user-images.githubusercontent.com/11475987/36631321-c57dbac6-19b0-11e8-9e8d-1a7cb5469dd9.png)

**Comment by Alkajato** [comment]
Is the window on the right vertically maximized? It's a feature in Plasma to make the corners sharp if a window is vertically maximized.

**Comment by Magentium-Chris** [comment]
Sorry for the late reply!! I've been super busy. That would be it! I use the KWin Quarter Tiling addon, which does maximize as vertical. This can be closed :D
