### ISSUE TITLE
"Keep above" button does not change the icon after being clicked

### ISSUE THREAD

**Issue by trmdi** [ishovkun/SierraBreeze#3]
Like the title says.

**Comment by GrayJack** [comment]
"On all desktops" button as well

**Comment by trmdi** [comment]
Yes, that will let the user know the state of that button.

**Comment by GrayJack** [comment]
Yeah! That's it, would be nice for the Keep below too, although I don't use this one

**Comment by GrayJack** [comment]
Maybe letting the buttons a little bit darker when clicked as well, like breezemite, although not really necessary, just having the visual hint when clicked should be enough
