### ISSUE TITLE
Once SSH'd a Konsole window no longer is treated correctly

### ISSUE THREAD

**Issue by krisives** [ishovkun/SierraBreeze#36]
Appears it's this line of code:

https://github.com/ishovkun/SierraBreeze/blob/380ac8fbceb3523140bebce95191a5f1828f7066/breezedecoration.cpp#L360-L363
A simple workaround is removing the check for colon (`:`) but a more comprehensive fix might be needed to actually check window class, etc.

**Comment by krisives** [comment]
![image](https://user-images.githubusercontent.com/153967/44313715-140a4380-a3c2-11e8-8f2d-4df01e70cee2.png)

**Comment by krisives** [comment]
![image](https://user-images.githubusercontent.com/153967/44313736-68adbe80-a3c2-11e8-82b8-3d8cc56864ca.png)

**Comment by trmdi** [comment]
@alex47 Can you please fix this?

**Comment by alex47** [comment]
@trmdi I fixed it in my fork which is still waiting for pull in https://github.com/ishovkun/SierraBreeze/pull/31
We are waiting for @ishovkun to review and merge it

Pros: more flexible Konsole titlebar transparency check, should work with your ssh use case
Cons: child windows of Konsole have transparent titlebars

**Comment by krisives** [comment]
I don't know the Kwin decoration system well enough, but is it possible to check if the window is actually a Konsole window without resorting to title bar hacks? For example the KDE Window Rules tool shows this information:

![image](https://user-images.githubusercontent.com/153967/44359718-884df100-a46d-11e8-931d-1ce7f026a845.png)

**Comment by krisives** [comment]
Appears this is the code where KDE does the "detect window" feature which shows that information above:
https://github.com/KDE/kwin/blob/1d71292e13fc820c12996d28d693d6e02c23defe/kcmkwin/kwinrules/detectwidget.cpp#L146

**Comment by krisives** [comment]
Appears this essentially works using this code:

https://github.com/KDE/kwin/blob/a3cff85e7aec126e089a1ee7685fa1ebfd84813a/kcmkwin/kwinrules/main.cpp#L83-L87

That code uses `ClientMachine` but some other code uses `KWindowInfo` - so I am not sure which is the "correct" way. In either case they seem to be wrappers that get the window ID of the underlying system and uses that to get the window class information.

**Comment by trmdi** [comment]
OT: Can you @krisives share your Konsole colorscheme (and vim color if it's available) ? It looks quite nice.

**Comment by krisives** [comment]
Sure! It's based on the "One Half Light" from the KDE store with some modifications to make it more readable:
https://gist.github.com/krisives/fa7dcd273737f7c43996c416592919c3
