### ISSUE TITLE
[Question] Unable to follow Documentation for ubuntu

### ISSUE THREAD

**Issue by kid101** [ishovkun/SierraBreeze#38]
where is "Your new decoration theme should appear in Settings → Application Style → Window Decorations"? I'm unable to find it in Ubuntu 18.4, can you let me know where is it? 
I've already made the build successfully. Do I need to install `kubuntu-desktop` on top of my Ubuntu?
or there is any other way to do it without installing kde?

**Comment by trmdi** [comment]
This is only for KDE (kwin). You can not use it with Gnome.
