### ISSUE TITLE
Colour scheme does not follow GTK / QT Theme

### ISSUE THREAD

**Issue by Magentium-Chris** [ishovkun/SierraBreeze#4]
So I set this up , thinking it would have a dark colour or a light colour depending on the QT / KDE Theme, but found that it seemed to keep the default Breeze theme colour scheme, where it is an odd blue/gray colour gradient, and looks rather poor.

Does this theme automatically update it's background colour / image and buttons dependant on the desktop theme or?

**Comment by trmdi** [comment]
You can change the titlebar color by changing the `Active/Inactive titlebar color` in `System Settings > Color`

**Comment by Magentium-Chris** [comment]
Oh Fantastic! Thank you so much. I feel so stupid, that was so simple!!!

**Comment by ishovkun** [comment]
Shall I close this?

**Comment by Magentium-Chris** [comment]
Go ahead :D It's really just user error haha 👍
