### ISSUE TITLE
The X on the close button isn't symmetrical

### ISSUE THREAD

**Issue by GrayJack** [ishovkun/SierraBreeze#5]
The X formed by the 2 lines in the close button isn't horizontally symmetrical

**Comment by ishovkun** [comment]
Please submit a screenshot. I don't see any asymmetry.

**Comment by GrayJack** [comment]
![sierrabreeze](https://user-images.githubusercontent.com/17973728/34021822-f6644e14-e122-11e7-96f2-5976761492fb.png)

**Comment by ishovkun** [comment]
Weird, I don't have this issue. Are you using the latest version?

**Comment by GrayJack** [comment]
Yeah, latest commit

**Comment by GrayJack** [comment]
Should I compile using another parameter in the cmake command that you recommend on readme?

**Comment by ishovkun** [comment]
Which parameter? Well, try to. 
Are you using a hi-DPI screen? Anything peculiar in your setup?

**Comment by GrayJack** [comment]
Not really, I'm using a 23" 1080p screen with nothing special

**Comment by ishovkun** [comment]
The cross in the Close button is defined in lines 214-215 of the file breezebutton.cpp. Try to play with the values. That's the only suggestion I can give you. Sorry about that, man. Another solution could be to set a larger width for the QPen object used to draw the hover hints.

**Comment by GrayJack** [comment]
When I change the "hint_pen" to "pen" in the line 213 it gets symmetrical, but the X flickers white before it gets black
There anything I can do to remove that flicker? Not really used to C++ and Qt libs... sorry

**Comment by ishovkun** [comment]
I just made a new commit with a new thickness for the hint pen. Try that out.

**Comment by GrayJack** [comment]
Just tested, and yeah, it got symmetrical
![screenshot_20171214_234221](https://user-images.githubusercontent.com/17973728/34022807-9e0da6b0-e128-11e7-84ea-029788a7c88c.png)

**Comment by ishovkun** [comment]
Awesome. I'm closing this then.
