### ISSUE TITLE
Questions about packaging SierraBreeze

### ISSUE THREAD

**Issue by Petross404** [ishovkun/SierraBreeze#7]
Hello, I am KDE/Gentoo user and I want to package SierraBreeze for portage. Can you please tell me under which license this software is?

Also is the list of the dependencies only that size or there are other packages too?

Thank you.

**Comment by ishovkun** [comment]
The license and dependencies are completely the same as for Breeze. I guess, to get the correct dependencies you'd need to look into the CMakeLists file.

**Comment by Petross404** [comment]
Thank you.
